version: '3'
services:
  app:
    build: .
    image: cf-3dgs
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./cache:/root/.cache
    command: bash
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
